# -*- coding: utf-8 -*-
"""Gerador de Senhas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wvFt3ZFwchojm_H3Eaq-a57aI0lGv0Gj
"""

import random
print('Gerador de Senhas')
print('\n======================================\n')
chars = 'abcdefghijklmnopqrstuvxyzABCDEFGHIJKLMNOPQRSTUVXYZ!@#$%*().,?0123456789'


length = input('Insira o comprimento da sua senha: ')
length = int(length)

print('\n Aqui esta sua senha: ')

for pwd in range(length):
  senha = ''
  for c in range(length):
    senha += random.choice(chars)
print(senha)
print('\n======================================')